// examples/tauri-solid-tanstack/src/main.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
import { createRouter, RouterProvider } from '@tanstack/solid-router';
import { render } from 'solid-js/web';
import { getRouter } from '#/router.tsx';
import { getQueryClient } from './integrations/tanstack-query/provider';
// import './styles.css';

// Create a new router instance
const router = getRouter();

const rootElement = document.getElementById('root')!;

if (!rootElement?.innerHTML) {
	render(
		() => (
			<QueryClientProvider client={getQueryClient()}>
				<RouterProvider router={router} />
			</QueryClientProvider>
		),
		rootElement,
	);
}

// examples/axum-react-query/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { getRouter } from "./router.tsx";
import { RouterProvider } from "@tanstack/react-router";
import { QueryClientProvider } from "@tanstack/react-query";
import { getQueryClient } from "#/integrations/tanstack-query/provider.ts";

const router = getRouter();

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <QueryClientProvider client={getQueryClient()}>
    <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
);
